name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
   
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        repo: ArnoRie/arnorie.github.io
        target_branch: master
        build_dir: dist
      env:
        GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}